//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabWorkflowManager.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ModuleStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModuleStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LabWorkflowManager.UI.Resources.ModuleStrings", typeof(ModuleStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new Definition.
        /// </summary>
        public static string BtnAdd {
            get {
                return ResourceManager.GetString("BtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string BtnAddDeploymentScript {
            get {
                return ResourceManager.GetString("BtnAddDeploymentScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string BtnConnect {
            get {
                return ResourceManager.GetString("BtnConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Definition.
        /// </summary>
        public static string BtnDelete {
            get {
                return ResourceManager.GetString("BtnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Definition.
        /// </summary>
        public static string BtnEdit {
            get {
                return ResourceManager.GetString("BtnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Build Defnitions.
        /// </summary>
        public static string BtnGenerateBuildDefnitions {
            get {
                return ResourceManager.GetString("BtnGenerateBuildDefnitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string BtnRemoveDeploymentScript {
            get {
                return ResourceManager.GetString("BtnRemoveDeploymentScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save all.
        /// </summary>
        public static string BtnSave {
            get {
                return ResourceManager.GetString("BtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TFS Connection.
        /// </summary>
        public static string GrpConnection {
            get {
                return ResourceManager.GetString("GrpConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string GrpDefinitionActions {
            get {
                return ResourceManager.GetString("GrpDefinitionActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build.
        /// </summary>
        public static string GrpDefinitionBuild {
            get {
                return ResourceManager.GetString("GrpDefinitionBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployment.
        /// </summary>
        public static string GrpDefinitionDeployment {
            get {
                return ResourceManager.GetString("GrpDefinitionDeployment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environments.
        /// </summary>
        public static string GrpDefinitionEnvironments {
            get {
                return ResourceManager.GetString("GrpDefinitionEnvironments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Settings.
        /// </summary>
        public static string GrpDefinitionGeneral {
            get {
                return ResourceManager.GetString("GrpDefinitionGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi Environemnt Workflow Definitions.
        /// </summary>
        public static string GrpDefinitions {
            get {
                return ResourceManager.GetString("GrpDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tests.
        /// </summary>
        public static string GrpDefinitionTests {
            get {
                return ResourceManager.GetString("GrpDefinitionTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Controller:.
        /// </summary>
        public static string LblBuildController {
            get {
                return ResourceManager.GetString("LblBuildController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Trigger Type:.
        /// </summary>
        public static string LblContinuousIntegrationType {
            get {
                return ResourceManager.GetString("LblContinuousIntegrationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Trigger Type Details:.
        /// </summary>
        public static string LblContinuousIntegrationTypeDetails {
            get {
                return ResourceManager.GetString("LblContinuousIntegrationTypeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string LblDefinitionDescription {
            get {
                return ResourceManager.GetString("LblDefinitionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id:.
        /// </summary>
        public static string LblDefinitionId {
            get {
                return ResourceManager.GetString("LblDefinitionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string LblDefinitionName {
            get {
                return ResourceManager.GetString("LblDefinitionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lab Process Template:.
        /// </summary>
        public static string LblLabProcesstemplate {
            get {
                return ResourceManager.GetString("LblLabProcesstemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F:.
        /// </summary>
        public static string LblScheduledDayFriday {
            get {
                return ResourceManager.GetString("LblScheduledDayFriday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M:.
        /// </summary>
        public static string LblScheduledDayMonday {
            get {
                return ResourceManager.GetString("LblScheduledDayMonday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S:.
        /// </summary>
        public static string LblScheduledDaySaturday {
            get {
                return ResourceManager.GetString("LblScheduledDaySaturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S:.
        /// </summary>
        public static string LblScheduledDaySunday {
            get {
                return ResourceManager.GetString("LblScheduledDaySunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T:.
        /// </summary>
        public static string LblScheduledDayThursday {
            get {
                return ResourceManager.GetString("LblScheduledDayThursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T:.
        /// </summary>
        public static string LblScheduledDayTuesday {
            get {
                return ResourceManager.GetString("LblScheduledDayTuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W:.
        /// </summary>
        public static string LblScheduledDayWednesday {
            get {
                return ResourceManager.GetString("LblScheduledDayWednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [New Definition].
        /// </summary>
        public static string NewDefinitionname {
            get {
                return ResourceManager.GetString("NewDefinitionname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definition: .
        /// </summary>
        public static string TitleEdit {
            get {
                return ResourceManager.GetString("TitleEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        public static string TitleManage {
            get {
                return ResourceManager.GetString("TitleManage", resourceCulture);
            }
        }
    }
}
